FORMAT: 1A
HOST: http://www.carlossouza.com/teamleader/

# Teamleader

This is a small (micro)service that calculates discounts for orders.

linked to:
https://github.com/teamleadercrm/coding-test/blob/master/1-discounts.md

## Questions Collection [/discounts]

### POST Discounts [POST]

+ Response 200 (application/json)

        [
            {
                "id": "Order Id"
            }
        ]